### PR TITLE
Support Virtual HDM

### PR DESCRIPTION
**Pull request by nkast**

### CODE REVIEW

**Comment by nkast** [comment]
Thanks @steemwheedle !

**Comment by cpt-max** [comment]
Thanks for your contribution!

**Comment by nkast** [comment]
You have a fine library here @steemwheedle 
I think you should post it at https://github.com/aloisdeniel/awesome-monogame. It would be a great help to many devs.

**Comment by cpt-max** [comment]
I just posted it. You gave it a nice facelift, thanks for that.

**Pull request merged**
